### ISSUE TITLE
Wrong Stats

### ISSUE THREAD

**Issue by david-one8** [Shobhit-Nagpal/gssoc-stats-gen#6]
If someone is not participated in Hack Web3 Conf. and he or she still selecting these options :-
Did you get the Postman badge?
Did you get the Hack Web3Conf badge?

Are getting wrong stats. fix it

![image](https://github.com/user-attachments/assets/19655e87-3512-4098-a015-21d66de4de57)

**Comment by Shobhit-Nagpal** [comment]
@david-one8  i'm aware that anyone can check this if they haven't done either or only one. that's why there's a terms of service page added. i trust the contributors to have basic integrity to be honest with their scores. adding on that, as this project isn't under gssoc, i don't have access to gssoc data

hope the context is clear now :))
